name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.7','3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - uses: rickstaa/action-black@v1
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
      - name: Install requirements
        run: python3 -m pip install --upgrade pip && pip3 install -r requirements.txt
      - name: Run pylint
        run: python3 -m pylint scheduledexecutor tests
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
      - name: Run pytest
        run: python3 -m pytest --cov=./ --cov-branch --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
