name: Lint
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-black@v1
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Run pylint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0
        with:
          args: python3 -m pip install --upgrade pip && pip3 install -r requirements.txt && python3 -m pylint scheduledexecutor
